name: CI
on:
  push:
    # branches:
    # - main
    tags:
      - v*

jobs:
  tags:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Extract version from tag
        id: extract_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        with:
          version: ${{ env.VERSION }}
          release: true
          body: |
            <p>
              <a target="_blank" href="https://apps.apple.com/app/quick-rss/6670696072" title="Quick RSS AppStore"><img alt="Quick RSS AppStore" src="https://jaywcjlove.github.io/sb/download/macos.svg" height="51">
              </a>
              <a target="_blank" href="https://apps.apple.com/app/regex-mate/6670696072?platform=iphone" title="Quick RSS for iOS"><img src="https://jaywcjlove.github.io/sb/download/appstore.svg" alt="Quick RSS for iOS" height="51"></a>
            </p>